# Generated by Django 5.2.4 on 2025-07-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_amigo_email_transitador_sobre_mi_hogar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('punto_de_encuentro', models.CharField(max_length=200)),
                ('dia_hora_preferencia', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
