# Generated by Django 5.2.4 on 2025-07-21 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_donacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='objeto_a_donar',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donacion',
            name='punto_de_encuentro',
            field=models.CharField(max_length=180),
        ),
    ]
