# Generated by Django 5.2.4 on 2025-07-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_donacion_objeto_a_donar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSrefugio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('objeto_solicitado', models.CharField(max_length=200)),
                ('punto_de_encuentro', models.CharField(max_length=180)),
                ('dia_hora_preferencia', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
